image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - master
  script:
    - sudo docker-compose kill
    - sudo docker-compose up -d
    - sleep 1
    - python3 automatedtest.py

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - sudo docker-compose kill
    - sudo docker-compose up -d

  environment: master
